import type {
  CourseApplication,
  ApplicationWorkspace,
  ShortlistedUniversity,
  UpcomingDeadline,
  ApplicationOverview,
} from './apply-types';

export const MOCK_APPLICATIONS: CourseApplication[] = [
  {
    id: 'app_1',
    userId: 'user_mock',
    universityName: 'The University of Manchester',
    courseName: 'BSc Computer Science',
    courseUrl: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/00560/bsc-computer-science/',
    degreeLevel: 'Undergraduate',
    subject: 'Computer Science',
    studyMode: 'Full-time',
    intake: 'Sep 2027',
    country: 'United Kingdom',
    countryFlag: '🇬🇧',
    applicationMethod: 'UCAS',
    applicationCode: 'G400',
    deadline: '2027-01-15',
    tuitionFee: '£28,000 / year',
    entryRequirementsSummary: 'A*AA including Mathematics',
    status: 'preparing',
    progressPercentage: 42,
    matchScore: 73,
    nextAction: 'Upload your personal statement draft',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Main_Building%2C_The_University_of_Manchester.jpg/1280px-Main_Building%2C_The_University_of_Manchester.jpg',
    sourceConfidence: 'high',
    createdAt: '2025-05-01T10:00:00Z',
    updatedAt: '2025-05-20T14:30:00Z',
  },
  {
    id: 'app_2',
    userId: 'user_mock',
    universityName: 'University of Cambridge',
    courseName: 'MEng Engineering',
    courseUrl: 'https://www.undergraduate.study.cam.ac.uk/courses/engineering',
    degreeLevel: 'Undergraduate',
    subject: 'Engineering',
    studyMode: 'Full-time',
    intake: 'Oct 2027',
    country: 'United Kingdom',
    countryFlag: '🇬🇧',
    applicationMethod: 'UCAS',
    applicationCode: 'H100',
    deadline: '2026-10-22',
    tuitionFee: '£9,535 / year',
    entryRequirementsSummary: 'A*A*A including Maths and Physics',
    status: 'preparing',
    progressPercentage: 28,
    matchScore: 61,
    nextAction: 'Register for admissions test',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/King%27s_College%2C_Cambridge_%28cropped%29.jpg/1280px-King%27s_College%2C_Cambridge_%28cropped%29.jpg',
    sourceConfidence: 'high',
    createdAt: '2025-05-05T09:00:00Z',
    updatedAt: '2025-05-22T11:00:00Z',
  },
  {
    id: 'app_3',
    userId: 'user_mock',
    universityName: 'VinUniversity',
    courseName: 'BSc Business Administration',
    courseUrl: 'https://vinuni.edu.vn/programs/business-administration/',
    degreeLevel: 'Undergraduate',
    subject: 'Business',
    studyMode: 'Full-time',
    intake: 'Aug 2027',
    country: 'Vietnam',
    countryFlag: '🇻🇳',
    applicationMethod: 'Direct Apply',
    deadline: '2027-04-30',
    tuitionFee: '$12,000 / year',
    entryRequirementsSummary: 'GPA 3.0+, SAT or equivalent',
    status: 'preparing',
    progressPercentage: 60,
    matchScore: 82,
    nextAction: 'Request academic reference',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Hanoi_panorama.jpg/1280px-Hanoi_panorama.jpg',
    sourceConfidence: 'medium',
    createdAt: '2025-04-20T08:00:00Z',
    updatedAt: '2025-05-25T16:00:00Z',
  },
];

export const MOCK_SHORTLISTED: ShortlistedUniversity[] = [
  {
    id: 'sl_1',
    universityId: 'uni_bristol',
    universityName: 'University of Bristol',
    country: 'United Kingdom',
    countryFlag: '🇬🇧',
    courseSearchUrl: 'https://www.bristol.ac.uk/study/undergraduate/',
  },
  {
    id: 'sl_2',
    universityId: 'uni_sydney',
    universityName: 'The University of Sydney',
    country: 'Australia',
    countryFlag: '🇦🇺',
    courseSearchUrl: 'https://www.sydney.edu.au/courses/search.html',
  },
];

export const MOCK_UPCOMING_DEADLINES: UpcomingDeadline[] = [
  {
    date: '2026-05-30',
    label: 'Scholarship deadline',
    universityName: 'VinUniversity',
    applicationId: 'app_3',
    daysLeft: 10,
  },
  {
    date: '2026-10-22',
    label: 'UCAS deadline',
    universityName: 'University of Cambridge',
    applicationId: 'app_2',
    daysLeft: 155,
  },
  {
    date: '2027-01-15',
    label: 'UCAS deadline',
    universityName: 'University of Manchester',
    applicationId: 'app_1',
    daysLeft: 240,
  },
];

export const MOCK_OVERVIEW: ApplicationOverview = {
  activeApplications: 3,
  submitted: 0,
  offersReceived: 0,
  tasksCompleted: 18,
  totalTasks: 54,
};

export const MOCK_WORKSPACE_APP1: ApplicationWorkspace = {
  application: MOCK_APPLICATIONS[0],
  keyFacts: {
    deadline: { value: '15 Jan 2027', confidence: 'high', sourceUrl: 'https://www.manchester.ac.uk/study/undergraduate/apply/how-to-apply/', label: '155 days left' },
    tuitionFee: { value: '£28,000 / year', confidence: 'medium', sourceUrl: 'https://www.manchester.ac.uk/study/undergraduate/tuition-fees/', label: 'View fees page' },
    applicationMethod: { value: 'UCAS', confidence: 'high', sourceUrl: 'https://www.ucas.com/', label: 'View how to apply' },
    entryRequirements: { value: 'A*AA including Mathematics', confidence: 'high', sourceUrl: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/00560/bsc-computer-science/entry-requirements/', label: 'View full requirements' },
    matchScore: 73,
    matchLabel: 'Good match',
  },
  stages: [
    {
      id: 'stage_research',
      applicationId: 'app_1',
      name: 'Research',
      order: 1,
      description: 'Learn about the course, the university, and the application process.',
      status: 'in_progress',
      isRequired: true,
      tasks: [
        {
          id: 'task_1_1',
          applicationId: 'app_1',
          stageId: 'stage_research',
          title: 'Review course overview and structure',
          description: 'Read the official course page and check the modules and teaching style.',
          dueDate: '2026-10-01',
          priority: 'medium',
          type: 'recommended',
          status: 'completed',
          sourceUrl: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/00560/bsc-computer-science/',
          confidence: 'high',
          createdBy: 'ai',
          createdAt: '2025-05-01T10:00:00Z',
          updatedAt: '2025-05-10T12:00:00Z',
        },
        {
          id: 'task_1_2',
          applicationId: 'app_1',
          stageId: 'stage_research',
          title: 'Watch: An intro to studying Computer Science at Manchester',
          description: 'Find the department video or open day recording.',
          dueDate: '2026-10-12',
          priority: 'low',
          type: 'recommended',
          status: 'not_started',
          confidence: 'medium',
          createdBy: 'ai',
          createdAt: '2025-05-01T10:00:00Z',
          updatedAt: '2025-05-01T10:00:00Z',
        },
        {
          id: 'task_1_3',
          applicationId: 'app_1',
          stageId: 'stage_research',
          title: 'Attend an online open day or webinar',
          description: 'Register and attend an official open day event to learn more.',
          priority: 'low',
          type: 'recommended',
          status: 'not_started',
          sourceUrl: 'https://www.manchester.ac.uk/study/undergraduate/visit/',
          confidence: 'high',
          createdBy: 'ai',
          createdAt: '2025-05-01T10:00:00Z',
          updatedAt: '2025-05-01T10:00:00Z',
        },
      ],
    },
    {
      id: 'stage_eligibility',
      applicationId: 'app_1',
      name: 'Check eligibility',
      order: 2,
      description: 'Confirm you meet all the academic, language, and subject requirements.',
      status: 'completed',
      isRequired: true,
      tasks: [
        {
          id: 'task_2_1',
          applicationId: 'app_1',
          stageId: 'stage_eligibility',
          title: 'Confirm academic requirements',
          description: 'Check your predicted or achieved grades against the offer requirements.',
          priority: 'high',
          type: 'required',
          status: 'completed',
          sourceUrl: 'https://www.manchester.ac.uk/study/undergraduate/courses/2027/00560/bsc-computer-science/entry-requirements/',
          confidence: 'high',
          createdBy: 'ai',
          createdAt: '2025-05-01T10:00:00Z',
          updatedAt: '2025-05-15T09:00:00Z',
        },
        {
          id: 'task_2_2',
          applicationId: 'app_1',
          stageId: 'stage_eligibility',
          title: 'Confirm English language requirements',
          description: 'Check IELTS or equivalent test requirements for international students.',
          priority: 'medium',
          type: 'required',
          status: 'completed',
          sourceUrl: 'https://www.manchester.ac.uk/study/international/english-language-requirements/',
          confidence: 'high',
          createdBy: 'ai',
          createdAt: '2025-05-01T10:00:00Z',
          updatedAt: '2025-05-15T09:00:00Z',
        },
      ],
    },
    {
      id: 'stage_documents',
      applicationId: 'app_1',
      name: 'Prepare documents',
      order: 3,
      description: 'Gather transcripts, references, and supporting documents.',
      status: 'in_progress',
      isRequired: true,
      tasks: [
        {
          id: 'task_3_1',
          applicationId: 'app_1',
          stageId: 'stage_documents',
          title: 'Prepare your academic transcript',
          description: 'Obtain official transcripts from your school or previous institution.',
          priority: 'high',
          type: 'required',
          status: 'completed',
          confidence: 'high',
          createdBy: 'ai',
          createdAt: '2025-05-01T10:00:00Z',
          updatedAt: '2025-05-18T10:00:00Z',
        },
        {
          id: 'task_3_2',
          applicationId: 'app_1',
          stageId: 'stage_documents',
          title: 'Request academic reference',
          description: 'Ask your teacher or academic supervisor for a reference letter.',
          priority: 'high',
          type: 'required',
          status: 'in_progress',
          confidence: 'high',
          createdBy: 'ai',
          createdAt: '2025-05-01T10:00:00Z',
          updatedAt: '2025-05-20T10:00:00Z',
        },
        {
          id: 'task_3_3',
          applicationId: 'app_1',
          stageId: 'stage_documents',
          title: 'Upload your personal statement draft',
          description: 'Write and refine your personal statement aligned to Computer Science.',
          priority: 'high',
          type: 'required',
          status: 'not_started',
          supportToolType: 'sop_maximiser',
          confidence: 'high',
          createdBy: 'ai',
          createdAt: '2025-05-01T10:00:00Z',
          updatedAt: '2025-05-01T10:00:00Z',
        },
      ],
    },
    {
      id: 'stage_improve',
      applicationId: 'app_1',
      name: 'Improve application',
      order: 4,
      description: 'Strengthen your personal statement, CV, and supporting materials.',
      status: 'in_progress',
      isRequired: true,
      tasks: [
        {
          id: 'task_4_1',
          applicationId: 'app_1',
          stageId: 'stage_improve',
          title: 'Run SOP through SOP Maximiser',
          description: 'Use Glowbal\'s AI tool to get feedback aligned to this specific course.',
          priority: 'high',
          type: 'recommended',
          status: 'not_started',
          supportToolType: 'sop_maximiser',
          confidence: 'high',
          createdBy: 'ai',
          createdAt: '2025-05-01T10:00:00Z',
          updatedAt: '2025-05-01T10:00:00Z',
        },
        {
          id: 'task_4_2',
          applicationId: 'app_1',
          stageId: 'stage_improve',
          title: 'Get mentor feedback on application',
          description: 'Book a session with a current Manchester student to review your application.',
          priority: 'medium',
          type: 'recommended',
          status: 'not_started',
          supportToolType: 'mentor',
          confidence: 'medium',
          createdBy: 'ai',
          createdAt: '2025-05-01T10:00:00Z',
          updatedAt: '2025-05-01T10:00:00Z',
        },
      ],
    },
    {
      id: 'stage_submit',
      applicationId: 'app_1',
      name: 'Submit',
      order: 5,
      description: 'Complete and submit your UCAS application.',
      status: 'not_started',
      isRequired: true,
      tasks: [],
    },
    {
      id: 'stage_interview',
      applicationId: 'app_1',
      name: 'Interview',
      order: 6,
      description: 'Prepare for and attend any interviews or assessments.',
      status: 'not_started',
      isRequired: false,
      tasks: [],
    },
    {
      id: 'stage_decision',
      applicationId: 'app_1',
      name: 'Decision',
      order: 7,
      description: 'Track your application outcome and respond to offers.',
      status: 'not_started',
      isRequired: true,
      tasks: [],
    },
  ],
};
