/**
 * Canonical target subjects used by the academic-profile picker.
 *
 * Values stay in English when they are saved so matching and AI prompts use a
 * stable vocabulary regardless of the interface language. The Vietnamese
 * labels are folded into the main i18n dictionary below.
 *
 * This is intentionally broad rather than a short "popular majors" list. It
 * covers the major fields represented across international university
 * catalogues; `Others` in the UI remains the escape hatch for emerging,
 * interdisciplinary, or institution-specific programme names.
 */

export type FieldOfStudyGroup = {
  label: string;
  labelVi: string;
  subjects: readonly (readonly [value: string, labelVi: string])[];
};

export const FIELD_OF_STUDY_GROUPS = [
  {
    label: 'Computing and Information Technology',
    labelVi: 'Máy tính và Công nghệ thông tin',
    subjects: [
      ['Computer Science', 'Khoa học máy tính'],
      ['Software Engineering', 'Kỹ thuật phần mềm'],
      ['Data Science', 'Khoa học dữ liệu'],
      ['Artificial Intelligence', 'Trí tuệ nhân tạo'],
      ['Cyber Security', 'An ninh mạng'],
      ['Information Technology', 'Công nghệ thông tin'],
      ['Information Systems', 'Hệ thống thông tin'],
      ['Informatics', 'Tin học'],
      ['Computer Engineering', 'Kỹ thuật máy tính'],
      ['Computer Graphics', 'Đồ họa máy tính'],
      ['Human Computer Interaction', 'Tương tác người - máy tính'],
      ['Game Development', 'Phát triển trò chơi'],
      ['Web Development', 'Phát triển web'],
      ['Cloud Computing', 'Điện toán đám mây'],
      ['Network Engineering', 'Kỹ thuật mạng'],
      ['Robotics', 'Robot học'],
      ['Bioinformatics', 'Tin sinh học'],
      ['Health Informatics', 'Tin học y tế'],
      ['Business Information Systems', 'Hệ thống thông tin kinh doanh'],
      ['Quantum Computing', 'Điện toán lượng tử'],
    ],
  },
  {
    label: 'Engineering',
    labelVi: 'Kỹ thuật',
    subjects: [
      ['Mechanical Engineering', 'Kỹ thuật cơ khí'],
      ['Civil Engineering', 'Kỹ thuật xây dựng'],
      ['Electrical Engineering', 'Kỹ thuật điện'],
      ['Electronic Engineering', 'Kỹ thuật điện tử'],
      ['Chemical Engineering', 'Kỹ thuật hóa học'],
      ['Aerospace Engineering', 'Kỹ thuật hàng không vũ trụ'],
      ['Biomedical Engineering', 'Kỹ thuật y sinh'],
      ['Automotive Engineering', 'Kỹ thuật ô tô'],
      ['Materials Engineering', 'Kỹ thuật vật liệu'],
      ['Industrial Engineering', 'Kỹ thuật công nghiệp'],
      ['Mechatronics', 'Cơ điện tử'],
      ['Environmental Engineering', 'Kỹ thuật môi trường'],
      ['Marine Engineering', 'Kỹ thuật hàng hải'],
      ['Agricultural Engineering', 'Kỹ thuật nông nghiệp'],
      ['Architectural Engineering', 'Kỹ thuật kiến trúc'],
      ['Structural Engineering', 'Kỹ thuật kết cấu'],
      ['Manufacturing Engineering', 'Kỹ thuật sản xuất'],
      ['Energy Engineering', 'Kỹ thuật năng lượng'],
      ['Nuclear Engineering', 'Kỹ thuật hạt nhân'],
      ['Petroleum Engineering', 'Kỹ thuật dầu khí'],
      ['Mining Engineering', 'Kỹ thuật khai khoáng'],
      ['Geological Engineering', 'Kỹ thuật địa chất'],
      ['Telecommunications Engineering', 'Kỹ thuật viễn thông'],
      ['Systems Engineering', 'Kỹ thuật hệ thống'],
      ['Transportation Engineering', 'Kỹ thuật giao thông'],
      ['Railway Engineering', 'Kỹ thuật đường sắt'],
      ['Naval Architecture', 'Kiến trúc tàu thủy'],
    ],
  },
  {
    label: 'Business, Economics and Finance',
    labelVi: 'Kinh doanh, Kinh tế và Tài chính',
    subjects: [
      ['Business', 'Kinh doanh'],
      ['Business Management', 'Quản trị kinh doanh'],
      ['Management', 'Quản trị'],
      ['International Business', 'Kinh doanh quốc tế'],
      ['Entrepreneurship', 'Khởi nghiệp'],
      ['Innovation Management', 'Quản trị đổi mới'],
      ['Accounting', 'Kế toán'],
      ['Finance', 'Tài chính'],
      ['Banking', 'Ngân hàng'],
      ['Investment Management', 'Quản lý đầu tư'],
      ['Financial Technology', 'Công nghệ tài chính'],
      ['Economics', 'Kinh tế học'],
      ['Econometrics', 'Kinh tế lượng'],
      ['Marketing', 'Tiếp thị'],
      ['Advertising', 'Quảng cáo'],
      ['Human Resource Management', 'Quản trị nhân lực'],
      ['Organizational Studies', 'Nghiên cứu tổ chức'],
      ['Business Analytics', 'Phân tích kinh doanh'],
      ['Supply Chain Management', 'Quản trị chuỗi cung ứng'],
      ['Logistics', 'Logistics'],
      ['Operations Management', 'Quản trị vận hành'],
      ['Project Management', 'Quản lý dự án'],
      ['Real Estate', 'Bất động sản'],
      ['Commerce', 'Thương mại'],
      ['E-Commerce', 'Thương mại điện tử'],
      ['Insurance', 'Bảo hiểm'],
      ['Actuarial Science', 'Khoa học định phí bảo hiểm'],
    ],
  },
  {
    label: 'Mathematics, Physical and Earth Sciences',
    labelVi: 'Toán học, Khoa học vật lý và Khoa học Trái Đất',
    subjects: [
      ['Mathematics', 'Toán học'],
      ['Applied Mathematics', 'Toán ứng dụng'],
      ['Statistics', 'Thống kê'],
      ['Operational Research', 'Nghiên cứu vận trù'],
      ['Physics', 'Vật lý'],
      ['Applied Physics', 'Vật lý ứng dụng'],
      ['Astronomy', 'Thiên văn học'],
      ['Astrophysics', 'Vật lý thiên văn'],
      ['Chemistry', 'Hóa học'],
      ['Applied Chemistry', 'Hóa học ứng dụng'],
      ['Earth Science', 'Khoa học Trái Đất'],
      ['Geology', 'Địa chất học'],
      ['Geophysics', 'Địa vật lý'],
      ['Meteorology', 'Khí tượng học'],
      ['Oceanography', 'Hải dương học'],
      ['Atmospheric Science', 'Khoa học khí quyển'],
      ['Materials Science', 'Khoa học vật liệu'],
      ['Nanotechnology', 'Công nghệ nano'],
      ['Forensic Science', 'Khoa học pháp y'],
      ['Geographic Information Science', 'Khoa học thông tin địa lý'],
      ['Physical Geography', 'Địa lý tự nhiên'],
      ['Hydrology', 'Thủy văn học'],
      ['Paleontology', 'Cổ sinh vật học'],
    ],
  },
  {
    label: 'Life, Agricultural and Environmental Sciences',
    labelVi: 'Khoa học sự sống, Nông nghiệp và Môi trường',
    subjects: [
      ['Biology', 'Sinh học'],
      ['Biochemistry', 'Hóa sinh'],
      ['Biotechnology', 'Công nghệ sinh học'],
      ['Biophysics', 'Lý sinh học'],
      ['Botany', 'Thực vật học'],
      ['Zoology', 'Động vật học'],
      ['Genetics', 'Di truyền học'],
      ['Genomics', 'Hệ gen học'],
      ['Microbiology', 'Vi sinh học'],
      ['Molecular Biology', 'Sinh học phân tử'],
      ['Cell Biology', 'Sinh học tế bào'],
      ['Ecology', 'Sinh thái học'],
      ['Evolutionary Biology', 'Sinh học tiến hóa'],
      ['Marine Biology', 'Sinh học biển'],
      ['Wildlife Biology', 'Sinh học động vật hoang dã'],
      ['Agriculture', 'Nông nghiệp'],
      ['Agricultural Science', 'Khoa học nông nghiệp'],
      ['Agribusiness', 'Kinh doanh nông nghiệp'],
      ['Animal Science', 'Khoa học động vật'],
      ['Food Science', 'Khoa học thực phẩm'],
      ['Food Technology', 'Công nghệ thực phẩm'],
      ['Forestry', 'Lâm nghiệp'],
      ['Horticulture', 'Khoa học làm vườn'],
      ['Plant Science', 'Khoa học thực vật'],
      ['Soil Science', 'Khoa học đất'],
      ['Fisheries', 'Thủy sản'],
      ['Veterinary Medicine', 'Thú y'],
      ['Environmental Science', 'Khoa học môi trường'],
      ['Sustainability', 'Phát triển bền vững'],
      ['Climate Change Studies', 'Nghiên cứu biến đổi khí hậu'],
      ['Conservation Biology', 'Sinh học bảo tồn'],
      ['Natural Resource Management', 'Quản lý tài nguyên thiên nhiên'],
    ],
  },
  {
    label: 'Medicine and Health Sciences',
    labelVi: 'Y khoa và Khoa học sức khỏe',
    subjects: [
      ['Medicine', 'Y khoa'],
      ['Nursing', 'Điều dưỡng'],
      ['Dentistry', 'Nha khoa'],
      ['Pharmacy', 'Dược học'],
      ['Public Health', 'Y tế công cộng'],
      ['Biomedical Science', 'Khoa học y sinh'],
      ['Neuroscience', 'Khoa học thần kinh'],
      ['Physiotherapy', 'Vật lý trị liệu'],
      ['Nutrition', 'Dinh dưỡng'],
      ['Dietetics', 'Dinh dưỡng học'],
      ['Occupational Therapy', 'Hoạt động trị liệu'],
      ['Optometry', 'Nhãn khoa'],
      ['Radiography', 'Kỹ thuật hình ảnh y học'],
      ['Midwifery', 'Hộ sinh'],
      ['Health Administration', 'Quản trị y tế'],
      ['Epidemiology', 'Dịch tễ học'],
      ['Speech and Language Therapy', 'Âm ngữ trị liệu'],
      ['Sports and Exercise Science', 'Khoa học thể thao và vận động'],
      ['Paramedic Science', 'Khoa học cấp cứu ngoại viện'],
      ['Medical Laboratory Science', 'Khoa học xét nghiệm y học'],
      ['Audiology', 'Thính học'],
      ['Anatomy', 'Giải phẫu học'],
      ['Physiology', 'Sinh lý học'],
      ['Pathology', 'Bệnh học'],
      ['Immunology', 'Miễn dịch học'],
      ['Pharmacology', 'Dược lý học'],
      ['Health Sciences', 'Khoa học sức khỏe'],
      ['Rehabilitation Science', 'Khoa học phục hồi chức năng'],
      ['Prosthetics and Orthotics', 'Chân tay giả và dụng cụ chỉnh hình'],
      ['Global Health', 'Sức khỏe toàn cầu'],
    ],
  },
  {
    label: 'Psychology and Social Sciences',
    labelVi: 'Tâm lý học và Khoa học xã hội',
    subjects: [
      ['Psychology', 'Tâm lý học'],
      ['Cognitive Science', 'Khoa học nhận thức'],
      ['Developmental Psychology', 'Tâm lý học phát triển'],
      ['Social Psychology', 'Tâm lý học xã hội'],
      ['Clinical Psychology', 'Tâm lý học lâm sàng'],
      ['Behavioral Science', 'Khoa học hành vi'],
      ['Sociology', 'Xã hội học'],
      ['Anthropology', 'Nhân học'],
      ['Archaeology', 'Khảo cổ học'],
      ['Criminology', 'Tội phạm học'],
      ['Human Geography', 'Địa lý nhân văn'],
      ['Demography', 'Nhân khẩu học'],
      ['Development Studies', 'Nghiên cứu phát triển'],
      ['Gender Studies', 'Nghiên cứu giới'],
      ['Social Policy', 'Chính sách xã hội'],
      ['Social Work', 'Công tác xã hội'],
      ['Urban Studies', 'Nghiên cứu đô thị'],
      ['Communication Studies', 'Nghiên cứu truyền thông'],
      ['International Development', 'Phát triển quốc tế'],
      ['Peace and Conflict Studies', 'Nghiên cứu hòa bình và xung đột'],
      ['Area Studies', 'Nghiên cứu khu vực'],
      ['Cultural Studies', 'Nghiên cứu văn hóa'],
      ['Disability Studies', 'Nghiên cứu khuyết tật'],
      ['Gerontology', 'Lão khoa xã hội'],
      ['Family Studies', 'Nghiên cứu gia đình'],
    ],
  },
  {
    label: 'Law, Politics and Public Policy',
    labelVi: 'Luật, Chính trị và Chính sách công',
    subjects: [
      ['Law', 'Luật'],
      ['Criminal Law', 'Luật hình sự'],
      ['Commercial Law', 'Luật thương mại'],
      ['Corporate Law', 'Luật doanh nghiệp'],
      ['International Law', 'Luật quốc tế'],
      ['Human Rights Law', 'Luật nhân quyền'],
      ['Intellectual Property Law', 'Luật sở hữu trí tuệ'],
      ['Environmental Law', 'Luật môi trường'],
      ['Politics', 'Chính trị học'],
      ['Political Science', 'Khoa học chính trị'],
      ['International Relations', 'Quan hệ quốc tế'],
      ['Public Policy', 'Chính sách công'],
      ['Public Administration', 'Hành chính công'],
      ['Security Studies', 'Nghiên cứu an ninh'],
      ['Military Studies', 'Nghiên cứu quân sự'],
      ['Diplomacy', 'Ngoại giao'],
      ['Governance', 'Quản trị công'],
    ],
  },
  {
    label: 'Education',
    labelVi: 'Giáo dục',
    subjects: [
      ['Education', 'Giáo dục'],
      ['Early Childhood Education', 'Giáo dục mầm non'],
      ['Primary Education', 'Giáo dục tiểu học'],
      ['Secondary Education', 'Giáo dục trung học'],
      ['Special Education', 'Giáo dục đặc biệt'],
      ['Higher Education', 'Giáo dục đại học'],
      ['Educational Psychology', 'Tâm lý học giáo dục'],
      ['Educational Leadership', 'Lãnh đạo giáo dục'],
      ['Curriculum and Instruction', 'Chương trình và phương pháp giảng dạy'],
      ['Teaching English to Speakers of Other Languages', 'Giảng dạy tiếng Anh cho người nói ngôn ngữ khác'],
      ['Language Education', 'Giáo dục ngôn ngữ'],
      ['Mathematics Education', 'Giáo dục toán học'],
      ['Science Education', 'Giáo dục khoa học'],
      ['Educational Technology', 'Công nghệ giáo dục'],
    ],
  },
  {
    label: 'Humanities, Languages and Religion',
    labelVi: 'Nhân văn, Ngôn ngữ và Tôn giáo',
    subjects: [
      ['History', 'Lịch sử'],
      ['Ancient History', 'Lịch sử cổ đại'],
      ['Art History', 'Lịch sử nghệ thuật'],
      ['Philosophy', 'Triết học'],
      ['Ethics', 'Đạo đức học'],
      ['Religious Studies', 'Nghiên cứu tôn giáo'],
      ['Theology', 'Thần học'],
      ['Classics', 'Nghiên cứu cổ điển'],
      ['Linguistics', 'Ngôn ngữ học'],
      ['English Language', 'Ngôn ngữ Anh'],
      ['English Literature', 'Văn học Anh'],
      ['Comparative Literature', 'Văn học so sánh'],
      ['Translation and Interpreting', 'Biên phiên dịch'],
      ['Modern Languages', 'Ngôn ngữ hiện đại'],
      ['French Studies', 'Nghiên cứu Pháp'],
      ['German Studies', 'Nghiên cứu Đức'],
      ['Spanish Studies', 'Nghiên cứu Tây Ban Nha'],
      ['Italian Studies', 'Nghiên cứu Ý'],
      ['Chinese Studies', 'Nghiên cứu Trung Quốc'],
      ['Japanese Studies', 'Nghiên cứu Nhật Bản'],
      ['Korean Studies', 'Nghiên cứu Hàn Quốc'],
      ['Arabic Studies', 'Nghiên cứu Ả Rập'],
      ['Russian Studies', 'Nghiên cứu Nga'],
      ['Vietnamese Studies', 'Việt Nam học'],
      ['Asian Studies', 'Nghiên cứu châu Á'],
      ['European Studies', 'Nghiên cứu châu Âu'],
      ['American Studies', 'Nghiên cứu Hoa Kỳ'],
      ['Middle Eastern Studies', 'Nghiên cứu Trung Đông'],
    ],
  },
  {
    label: 'Arts, Design and Media',
    labelVi: 'Nghệ thuật, Thiết kế và Truyền thông',
    subjects: [
      ['Fine Art', 'Mỹ thuật'],
      ['Visual Arts', 'Nghệ thuật thị giác'],
      ['Design', 'Thiết kế'],
      ['Graphic Design', 'Thiết kế đồ họa'],
      ['Industrial Design', 'Thiết kế công nghiệp'],
      ['Product Design', 'Thiết kế sản phẩm'],
      ['Fashion Design', 'Thiết kế thời trang'],
      ['Textile Design', 'Thiết kế dệt may'],
      ['Interior Design', 'Thiết kế nội thất'],
      ['Interaction Design', 'Thiết kế tương tác'],
      ['User Experience Design', 'Thiết kế trải nghiệm người dùng'],
      ['Animation', 'Hoạt hình'],
      ['Illustration', 'Minh họa'],
      ['Photography', 'Nhiếp ảnh'],
      ['Film', 'Điện ảnh'],
      ['Film Production', 'Sản xuất phim'],
      ['Media Studies', 'Nghiên cứu truyền thông đại chúng'],
      ['Digital Media', 'Truyền thông số'],
      ['Journalism', 'Báo chí'],
      ['Public Relations', 'Quan hệ công chúng'],
      ['Publishing', 'Xuất bản'],
      ['Creative Writing', 'Viết sáng tạo'],
      ['Drama', 'Kịch nghệ'],
      ['Theatre Studies', 'Nghiên cứu sân khấu'],
      ['Dance', 'Múa'],
      ['Music', 'Âm nhạc'],
      ['Music Production', 'Sản xuất âm nhạc'],
      ['Sound Engineering', 'Kỹ thuật âm thanh'],
      ['Performing Arts', 'Nghệ thuật biểu diễn'],
      ['Game Design', 'Thiết kế trò chơi'],
    ],
  },
  {
    label: 'Architecture, Planning and Built Environment',
    labelVi: 'Kiến trúc, Quy hoạch và Môi trường xây dựng',
    subjects: [
      ['Architecture', 'Kiến trúc'],
      ['Landscape Architecture', 'Kiến trúc cảnh quan'],
      ['Urban Planning', 'Quy hoạch đô thị'],
      ['Regional Planning', 'Quy hoạch vùng'],
      ['Construction Management', 'Quản lý xây dựng'],
      ['Building Services Engineering', 'Kỹ thuật hệ thống tòa nhà'],
      ['Quantity Surveying', 'Kinh tế xây dựng'],
      ['Surveying', 'Trắc địa'],
      ['Property Management', 'Quản lý bất động sản'],
      ['Housing Studies', 'Nghiên cứu nhà ở'],
      ['Historic Preservation', 'Bảo tồn di sản kiến trúc'],
    ],
  },
  {
    label: 'Hospitality, Tourism and Services',
    labelVi: 'Khách sạn, Du lịch và Dịch vụ',
    subjects: [
      ['Hospitality Management', 'Quản trị khách sạn'],
      ['Tourism Management', 'Quản trị du lịch'],
      ['Event Management', 'Quản trị sự kiện'],
      ['Culinary Arts', 'Nghệ thuật ẩm thực'],
      ['Sports Management', 'Quản lý thể thao'],
      ['Leisure Management', 'Quản lý giải trí'],
      ['Aviation Management', 'Quản lý hàng không'],
      ['Maritime Management', 'Quản lý hàng hải'],
      ['Retail Management', 'Quản lý bán lẻ'],
      ['Customer Experience Management', 'Quản lý trải nghiệm khách hàng'],
    ],
  },
  {
    label: 'Interdisciplinary and General Studies',
    labelVi: 'Liên ngành và Đại cương',
    subjects: [
      ['Liberal Arts', 'Khai phóng'],
      ['Liberal Studies', 'Nghiên cứu khai phóng'],
      ['General Studies', 'Nghiên cứu đại cương'],
      ['Interdisciplinary Studies', 'Nghiên cứu liên ngành'],
      ['Philosophy, Politics and Economics', 'Triết học, Chính trị và Kinh tế'],
      ['Science, Technology and Society', 'Khoa học, Công nghệ và Xã hội'],
      ['Global Studies', 'Nghiên cứu toàn cầu'],
      ['International Studies', 'Nghiên cứu quốc tế'],
      ['Library and Information Science', 'Thư viện và Khoa học thông tin'],
      ['Museum Studies', 'Bảo tàng học'],
      ['Heritage Studies', 'Nghiên cứu di sản'],
      ['Emergency and Disaster Management', 'Quản lý khẩn cấp và thảm họa'],
      ['Environmental Studies', 'Nghiên cứu môi trường'],
      ['Renewable Energy', 'Năng lượng tái tạo'],
      ['Marine Studies', 'Nghiên cứu biển'],
    ],
  },
] as const satisfies readonly FieldOfStudyGroup[];

export const FIELD_OF_STUDY_VALUES = FIELD_OF_STUDY_GROUPS.flatMap((group) =>
  group.subjects.map(([value]) => value),
);

export const FIELD_OF_STUDY_SET: ReadonlySet<string> = new Set(FIELD_OF_STUDY_VALUES);

const fieldOfStudyTranslationEntries: Array<readonly [string, string]> = [];
for (const group of FIELD_OF_STUDY_GROUPS) {
  fieldOfStudyTranslationEntries.push([group.label, group.labelVi]);
  fieldOfStudyTranslationEntries.push(...group.subjects);
}

export const FIELD_OF_STUDY_TRANSLATIONS: Readonly<Record<string, string>> =
  Object.fromEntries(fieldOfStudyTranslationEntries);
