export const studyLevels = [
  { value: 'undergraduate', label: 'Undergraduate' },
  { value: 'postgraduate', label: 'Postgraduate' },
  { value: 'phd', label: 'PhD' },
];

export const regions = [
  {
    name: 'UK & Ireland',
    countries: ['United Kingdom', 'Ireland'],
  },
  {
    name: 'Europe',
    countries: ['Netherlands', 'Germany', 'France', 'Sweden', 'Switzerland', 'Spain', 'Italy'],
  },
  {
    name: 'North America',
    countries: ['United States', 'Canada'],
  },
  {
    name: 'Asia-Pacific',
    countries: ['Singapore', 'Australia', 'New Zealand', 'Japan', 'South Korea', 'Hong Kong'],
  },
  {
    name: 'Middle East',
    countries: ['United Arab Emirates', 'Qatar'],
  },
];

export const campusStyles = ['Big city', 'Campus town', 'Quiet / green', 'Flexible'];

export const supportNeeds = [
  'Applications and deadlines',
  'Choosing the right country',
  'Budget / affordability',
  'Confidence and direction',
  'Scholarships and funding',
  'Parents / family alignment',
];

export const subjectFamilies = [
  {
    key: 'technology',
    label: 'Technology',
    children: [
      'Computer Science',
      'Software Engineering',
      'Data Science',
      'Artificial Intelligence',
      'Cyber Security',
      'Information Technology',
      'Game Development',
      'Web Development',
      'Cloud Computing',
      'Human Computer Interaction',
      'Robotics',
      'Computer Engineering',
    ],
  },
  {
    key: 'engineering',
    label: 'Engineering',
    children: [
      'Mechanical Engineering',
      'Civil Engineering',
      'Electrical Engineering',
      'Chemical Engineering',
      'Aerospace Engineering',
      'Biomedical Engineering',
      'Automotive Engineering',
      'Materials Engineering',
      'Industrial Engineering',
      'Mechatronics',
      'Environmental Engineering',
      'Marine Engineering',
    ],
  },
  {
    key: 'business',
    label: 'Business',
    children: [
      'Business Management',
      'Finance',
      'Economics',
      'Marketing',
      'Entrepreneurship',
      'Accounting',
      'International Business',
      'Business Analytics',
      'Supply Chain Management',
      'Human Resource Management',
      'Management',
      'Hospitality Management',
    ],
  },
  {
    key: 'arts',
    label: 'Arts & Creative',
    children: [
      'Drama',
      'Music',
      'Design',
      'Fine Art',
      'Film',
      'English Literature',
      'Creative Writing',
      'Media Studies',
      'Graphic Design',
      'Animation',
      'Architecture',
      'Fashion Design',
    ],
  },
  {
    key: 'social',
    label: 'Social Sciences',
    children: [
      'Psychology',
      'Politics',
      'International Relations',
      'Sociology',
      'Law',
      'History',
      'Philosophy',
      'Anthropology',
      'Criminology',
      'Geography',
      'Education',
      'English Language',
    ],
  },
  {
    key: 'health',
    label: 'Health and Science',
    children: [
      'Medicine',
      'Biology',
      'Neuroscience',
      'Public Health',
      'Pharmacy',
      'Nursing',
      'Dentistry',
      'Biomedical Science',
      'Physiotherapy',
      'Nutrition',
      'Mathematics',
      'Physics',
      'Chemistry',
    ],
  },
];

export const onboardingSteps = [
  {
    key: 'study_level',
    eyebrow: 'Step 1',
    title: 'What level are you aiming for?',
    description: 'Start with the path you are actually planning now.',
    visualTitle: 'Choose your route',
    visualBody: 'We begin by understanding the kind of academic journey you are stepping into.',
    accent: 'from-cyan-400/30 via-sky-400/10 to-transparent',
  },
  {
    key: 'subjects',
    eyebrow: 'Step 2',
    title: 'Which subject worlds pull you in?',
    description: 'Choose the broad themes first, then tap into specific subjects.',
    visualTitle: 'Find your curiosity',
    visualBody: 'This should feel like discovery, not paperwork. Explore the areas that genuinely energise you.',
    accent: 'from-fuchsia-400/25 via-violet-400/10 to-transparent',
  },
  {
    key: 'countries',
    eyebrow: 'Step 3',
    title: 'Which parts of the world feel right for you?',
    description: 'Think globally, then narrow to the places that feel exciting or realistic.',
    visualTitle: 'Map your possibilities',
    visualBody: 'Glowbal should help students think beyond defaults without feeling overwhelmed.',
    accent: 'from-emerald-400/25 via-cyan-400/10 to-transparent',
  },
  {
    key: 'budget',
    eyebrow: 'Step 4',
    title: 'What budget feels realistic?',
    description: 'Slide to the cost range that feels comfortable right now.',
    visualTitle: 'Stay grounded',
    visualBody: 'A strong shortlist should be ambitious but still realistic on cost and access.',
    accent: 'from-amber-300/25 via-orange-300/10 to-transparent',
  },
  {
    key: 'campus',
    eyebrow: 'Step 5',
    title: 'What kind of environment suits you?',
    description: 'Big city, campus town, somewhere quiet, or a flexible mix?',
    visualTitle: 'Match the vibe',
    visualBody: 'Course fit matters, but so does where you will live, grow, and feel at home.',
    accent: 'from-indigo-400/25 via-blue-400/10 to-transparent',
  },
  {
    key: 'support',
    eyebrow: 'Step 6',
    title: 'Where do you most want support?',
    description: 'Pick the areas where guidance would genuinely help.',
    visualTitle: 'Know what you need',
    visualBody: 'The best product feels supportive, not judgemental. This helps us guide well.',
    accent: 'from-rose-400/25 via-pink-400/10 to-transparent',
  },
  {
    key: 'goals',
    eyebrow: 'Step 7',
    title: 'What kind of future are you trying to build?',
    description: 'This helps Glowbal feel more personal and much less generic.',
    visualTitle: 'Aim at something meaningful',
    visualBody: 'Students are not just choosing courses. They are choosing a direction for their life.',
    accent: 'from-cyan-300/25 via-white/5 to-transparent',
  },
];
