-- Additive staging for bounded structured rows derived from durable external
-- raw objects.  This table is intentionally separate from assertions and
-- canonical/product tables; rows retain provider/member/raw lineage only.

begin;

create table if not exists public.crawl_external_structured_rows (
  id bigint generated by default as identity primary key,
  run_id text not null,
  run_key text,
  derived_resource_id text not null,
  raw_document_id text,
  provider_id text,
  dataset_id text,
  source_class text,
  source_authority text,
  source_relationship text,
  raw_object_key text,
  raw_content_hash text,
  archive_member text,
  member_content_type text,
  institution_id text,
  programme_id text,
  academic_cycle text,
  rows jsonb not null default '[]'::jsonb,
  rows_scanned integer not null default 0,
  rows_retained integer not null default 0,
  partial boolean not null default false,
  bounded_reason text,
  bytes_scanned bigint,
  lineage jsonb not null default '{}'::jsonb,
  retrieved_at timestamptz,
  created_at timestamptz not null default now(),
  unique (run_id, derived_resource_id)
);

create index if not exists idx_crawl_external_structured_provider
  on public.crawl_external_structured_rows(run_id, provider_id, dataset_id);
create index if not exists idx_crawl_external_structured_raw
  on public.crawl_external_structured_rows(run_id, raw_content_hash);
create index if not exists idx_crawl_external_structured_institution
  on public.crawl_external_structured_rows(run_id, institution_id);

alter table public.crawl_external_structured_rows enable row level security;
revoke all on table public.crawl_external_structured_rows from anon, authenticated;
grant all on table public.crawl_external_structured_rows to service_role;
grant usage, select on all sequences in schema public to service_role;

comment on table public.crawl_external_structured_rows is
  'Bounded structured rows derived from durable external raw objects; never canonical truth.';
comment on column public.crawl_external_structured_rows.raw_object_key is
  'Durable object-store locator for the immutable raw source.';
comment on column public.crawl_external_structured_rows.lineage is
  'JSON lineage from row/member to raw object, provider, dataset, and run.';

commit;
