-- ============================================================================
-- GLOWBAL — GEO NEWS CMS MIGRATION
-- Run this in the Supabase SQL Editor (Dashboard → SQL Editor → New Query),
-- AFTER supabase-schema.sql (this file references public.student_profiles for
-- the admin-author relationship and auth.users for authorship).
-- Safe to re-run: every object guards with `if not exists` / `do $$` blocks.
--
-- WHY THIS EXISTS
--   GLOWBAL News articles ("GEO guides") have historically lived as markdown
--   files committed to git by the GEO content pipeline
--   (.github/workflows/geo-content-pipeline.yml) and rendered via static
--   generation from src/lib/geo-content.ts.
--
--   The CMS makes the database the canonical store so that:
--     - admins can author / edit / publish / archive articles in-site, live,
--     - the GEO pipeline writes generated drafts straight into the DB,
--     - articles can be linked together (geo_article_links) to strengthen the
--       internal GEO graph that AI search engines reward.
--
--   The markdown files become an import/export format (see backfill notes in
--   GEO_CMS_SPEC.md), not the source of truth.
-- ============================================================================

-- ── 1. Enums ────────────────────────────────────────────────────────────────
do $$
begin
  if not exists (select 1 from pg_type where typname = 'geo_article_status') then
    -- draft     → editable, hidden from the public site
    -- published → live and crawlable
    -- archived  → retired, hidden, but kept for history / un-archive
    create type geo_article_status as enum ('draft', 'published', 'archived');
  end if;

  if not exists (select 1 from pg_type where typname = 'geo_article_source') then
    -- manual   → authored by an admin in the CMS
    -- pipeline → generated by the GEO content pipeline
    create type geo_article_source as enum ('manual', 'pipeline');
  end if;
end $$;

-- pg_trgm powers fuzzy title search in the admin list (Supabase ships it).
create extension if not exists pg_trgm;

-- ── 2. geo_articles ───────────────────────────────────────────────────────────
-- One row per GLOWBAL News / guide article. `body` is markdown (the same
-- prose format the pipeline already produces); `meta` is a jsonb catch-all
-- that preserves the richer GeoPageMetadata shape (supportCards, supportAssets,
-- toc, schema.org blocks, openGraph, canonicalUrl, pageType, heroImagePrompt …)
-- without forcing a column per field.
create table if not exists public.geo_articles (
  id                    uuid primary key default gen_random_uuid(),

  -- Identity / routing
  slug                  text not null unique,
  title                 text not null,

  -- Display copy
  description           text,                       -- subtitle / dek
  excerpt               text,                       -- card + meta description fallback
  key_takeaway          text,                       -- highlighted callout

  -- Body (markdown). Rendered by the existing ArticleBody component.
  body                  text not null default '',

  -- Taxonomy
  topic                 text not null default 'All topics',
  tags                  text[] not null default '{}',

  -- Hero imagery (URLs under /generated/news or Supabase Storage)
  hero_image            text,
  hero_image_style      text check (hero_image_style in ('ai', 'svg-fallback')),

  -- Reading estimate (minutes). Null → derive from body at read time.
  reading_time_minutes  int,

  -- Rich SEO/GEO metadata that doesn't deserve its own column (yet).
  meta                  jsonb not null default '{}',

  -- Workflow
  status                geo_article_status not null default 'draft',
  source                geo_article_source not null default 'manual',

  -- Provenance: link a pipeline-generated article back to its topic cluster.
  pipeline_cluster_id   text,

  -- Authorship: the admin who created/last-owned it (null for pipeline rows).
  author_id             uuid references auth.users(id) on delete set null,

  published_at          timestamptz,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

create index if not exists idx_geo_articles_status       on public.geo_articles(status);
create index if not exists idx_geo_articles_topic        on public.geo_articles(topic);
create index if not exists idx_geo_articles_published_at on public.geo_articles(published_at desc);
create index if not exists idx_geo_articles_tags         on public.geo_articles using gin (tags);
create index if not exists idx_geo_articles_title_trgm   on public.geo_articles using gin (title gin_trgm_ops);

-- ── 3. geo_article_links (multi-article graph for GEO) ────────────────────────
-- Directed, typed edges between articles. Powers "Related articles", topic
-- clusters/hubs, prerequisite/next reading chains, and the internal-link graph
-- that AI search engines use to understand and surface GLOWBAL.
create table if not exists public.geo_article_links (
  from_article_id  uuid not null references public.geo_articles(id) on delete cascade,
  to_article_id    uuid not null references public.geo_articles(id) on delete cascade,

  -- related      → generic "you might also read"
  -- cluster      → both belong to the same topic hub/pillar
  -- prerequisite → read `to` before `from`
  -- next         → suggested next article after `from`
  -- cites        → `from` references `to` as a source/citation
  relation         text not null default 'related'
                     check (relation in ('related', 'cluster', 'prerequisite', 'next', 'cites')),

  -- Ordering / strength hint for surfacing (higher = stronger).
  weight           int not null default 0,
  created_at       timestamptz not null default now(),

  primary key (from_article_id, to_article_id, relation),
  constraint geo_article_links_no_self check (from_article_id <> to_article_id)
);

create index if not exists idx_geo_links_to on public.geo_article_links(to_article_id);

-- ── 4. updated_at trigger ─────────────────────────────────────────────────────
create or replace function public.touch_geo_articles_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  -- Stamp published_at the first time a row goes live.
  if new.status = 'published' and old.status is distinct from 'published' and new.published_at is null then
    new.published_at = now();
  end if;
  return new;
end;
$$;

drop trigger if exists trg_touch_geo_articles on public.geo_articles;
create trigger trg_touch_geo_articles
  before update on public.geo_articles
  for each row
  execute function public.touch_geo_articles_updated_at();

-- ── 5. RLS ───────────────────────────────────────────────────────────────────
-- Mirror the scholarships pattern: the public can read PUBLISHED rows only;
-- the service_role (used by admin-gated API routes + the GEO pipeline) has
-- full access. Admin writes flow through createAdminClient(), so we do NOT
-- need a per-row is_admin write policy here — and that also keeps env-based
-- bootstrap admins (ADMIN_USER_IDS) working without a student_profiles row.
--
-- News/guides pages are public (crawlable by AI search), so published read is
-- granted to BOTH anon and authenticated, unlike the authenticated-only
-- scholarships table.
alter table public.geo_articles enable row level security;
alter table public.geo_article_links enable row level security;

do $$
begin
  -- Anyone (including anonymous crawlers) can read published articles.
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'geo_articles'
      and policyname = 'Public can read published articles'
  ) then
    create policy "Public can read published articles"
      on public.geo_articles for select
      to anon, authenticated
      using (status = 'published');
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'geo_articles'
      and policyname = 'Service role full access to geo_articles'
  ) then
    create policy "Service role full access to geo_articles"
      on public.geo_articles for all
      to service_role
      using (true)
      with check (true);
  end if;

  -- Links are readable when their source article is published.
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'geo_article_links'
      and policyname = 'Public can read links for published articles'
  ) then
    create policy "Public can read links for published articles"
      on public.geo_article_links for select
      to anon, authenticated
      using (exists (
        select 1 from public.geo_articles a
        where a.id = geo_article_links.from_article_id
          and a.status = 'published'
      ));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'geo_article_links'
      and policyname = 'Service role full access to geo_article_links'
  ) then
    create policy "Service role full access to geo_article_links"
      on public.geo_article_links for all
      to service_role
      using (true)
      with check (true);
  end if;
end $$;
