'use client';

import { useLanguage } from '@/lib/i18n';

const VI: Record<string, string> = {
  'Edit article': 'Chỉnh sửa bài viết',
  'New article': 'Bài viết mới',
  'Update your story, then preview it before publishing.': 'Cập nhật bài viết, xem trước rồi mới đăng.',
  'Create a clear, engaging GLOWBAL News story.': 'Tạo bài viết GLOWBAL News rõ ràng và thu hút.',
  'Back to News': 'Quay lại Tin tức',
  'Saving article': 'Đang lưu bài viết',
  'Complete the publish checklist': 'Hoàn tất danh sách kiểm tra trước khi đăng',
  'Save failed': 'Lưu thất bại',
  'Image upload failed': 'Tải ảnh thất bại',
  'Another admin updated this article. Reload the page before saving again.': 'Một quản trị viên khác đã cập nhật bài viết. Hãy tải lại trang trước khi lưu.',
  Story: 'Bài viết',
  'Write for people first. The public article will keep the same formatting.': 'Viết cho người đọc trước. Bài công khai sẽ giữ nguyên định dạng.',
  'A clear headline your reader can understand': 'Tiêu đề rõ ràng, dễ hiểu',
  'Summarize the story in one sentence.': 'Tóm tắt bài viết trong một câu.',
  'The one idea readers should remember.': 'Ý tưởng quan trọng nhất người đọc cần nhớ.',
  'Article body': 'Nội dung bài viết',
  '{minutes} min read · formatting toolbar enabled': '{minutes} phút đọc · đã bật thanh định dạng',
  'Use the image button to upload an inline image. Add descriptive alt text in the image dialog.': 'Dùng nút hình ảnh để tải ảnh trong bài. Thêm mô tả alt trong hộp thoại hình ảnh.',
  'Advanced GEO settings': 'Cài đặt GEO nâng cao',
  'Save the draft first to add related articles.': 'Hãy lưu bản nháp trước để thêm bài liên quan.',
  'These details help readers find and trust the story.': 'Các thông tin này giúp người đọc tìm và tin tưởng bài viết.',
  'Choose a topic': 'Chọn chủ đề',
  'Separate tags with commas.': 'Phân cách thẻ bằng dấu phẩy.',
  'Card excerpt': 'Mô tả thẻ bài viết',
  'Shown on News cards and search results.': 'Hiển thị trên thẻ Tin tức và kết quả tìm kiếm.',
  'Hero image': 'Ảnh đại diện',
  'A strong image gives the story a clear entry point.': 'Ảnh đại diện tốt giúp bài viết thu hút ngay từ đầu.',
  'Hero image preview': 'Xem trước ảnh đại diện',
  'Click to upload a hero image': 'Nhấp để tải ảnh đại diện',
  'Hero image alt text': 'Văn bản alt ảnh đại diện',
  'Describe what the image shows': 'Mô tả nội dung ảnh',
  'Required before publishing.': 'Bắt buộc trước khi đăng.',
  'Search preview': 'Xem trước tìm kiếm',
  'Control the URL and search snippet without touching code.': 'Chỉnh URL và mô tả tìm kiếm mà không cần sửa mã.',
  'Article URL': 'URL bài viết',
  'Hide technical metadata': 'Ẩn metadata kỹ thuật',
  'Show technical metadata': 'Hiện metadata kỹ thuật',
  'Internal notes': 'Ghi chú nội bộ',
  Preview: 'Xem trước',
  Publish: 'Đăng bài',
  'All changes saved': 'Đã lưu tất cả thay đổi',
  'Unsaved changes': 'Có thay đổi chưa lưu',
  'Needs attention': 'Cần kiểm tra',
  'Save draft': 'Lưu bản nháp',
  Saving: 'Đang lưu…',
  Draft: 'Bản nháp',
  Published: 'Đã đăng',
  Archived: 'Đã lưu trữ',
  'Updating the article': 'Đang cập nhật bài viết',
  'Import failed': 'Nhập bài viết thất bại',
  'Imported {total} file article(s): {created} created, {updated} updated, {skipped} skipped.': 'Đã nhập {total} bài: {created} tạo mới, {updated} cập nhật, {skipped} bỏ qua.',
  'Update failed': 'Cập nhật thất bại',
  'Delete failed': 'Xóa thất bại',
  'Delete “{title}”? This cannot be undone.': 'Xóa “{title}”? Thao tác này không thể hoàn tác.',
  'Importing…': 'Đang nhập…',
  'Import from files': 'Nhập từ tệp',
  'Import legacy articles': 'Nhập bài viết cũ',
  '{count} article(s)': '{count} bài viết',
  'Search articles': 'Tìm bài viết',
  'Search by title, topic, or URL': 'Tìm theo tiêu đề, chủ đề hoặc URL',
  'All statuses': 'Tất cả trạng thái',
  'All topics': 'Tất cả chủ đề',
  'No articles yet. Create your first one.': 'Chưa có bài viết. Hãy tạo bài đầu tiên.',
  'No articles match these filters.': 'Không có bài viết phù hợp với bộ lọc.',
  Updated: 'Cập nhật',
  Actions: 'Thao tác',
  Edit: 'Chỉnh sửa',
  Unpublish: 'Gỡ đăng',
  Delete: 'Xóa',
  'Preview — this {status} article is not visible to the public yet.': 'Xem trước — bài viết {status} này chưa hiển thị công khai.',
  'Back to editor': 'Quay lại trình soạn thảo',
  '{minutes} min read': '{minutes} phút đọc',
  'Key takeaway': 'Điểm chính',
  'Untitled article': 'Bài viết chưa có tiêu đề',
  'The article body could not be read. Review it before saving.': 'Không thể đọc nội dung bài viết. Hãy kiểm tra trước khi lưu.',
};

export function useNewsCopy() {
  const { lang, t } = useLanguage();
  return (english: string, vars?: Record<string, string | number>) => {
    const translated = lang === 'vi' ? VI[english] ?? t(english) : english;
    return vars ? translated.replace(/\{(\w+)\}/g, (_, key) => key in vars ? String(vars[key]) : `{${key}}`) : translated;
  };
}
