-- ─────────────────────────────────────────────────────────────────────────────
-- Give the Home consultation form's three extra answers their own columns.
--
-- WHY. The sales-journey Home (2026-09-27) asks for destination, budget and
-- package on top of the name / email / phone / date of birth this table already
-- held (sql/supabase-waitlist.sql). Until this runs those three ride in `notes`
-- as one labelled line —
--
--     Destination: … · Budget: … · Package: … · Source: Home consultation form
--
-- — which a person can read but nobody can filter or count by.
--
-- VALUES. The only writer is `recordWaitlistSignup`
-- (src/features/marketing/api), and only after the shared Zod validator
-- (`validateConsultation`, src/features/marketing/domain/consultation.ts) has
-- passed:
--
--     destination  free text, trimmed, required by the form
--     budget       'under-300m' | '300-500m' | '500-800m' | 'over-800m' | null
--     package      'starter' | 'yearly' | 'premium' | null
--
-- NO CHECK CONSTRAINTS, on purpose: the package list follows the owner's PDF
-- and has not been reconciled with src/lib/plus.ts yet (docs/current-status.md,
-- "Pricing ≠ checkout"). A constraint would turn renaming a package into a
-- second migration that has to run in lock-step with the deploy.
--
-- `notes` keeps its line (it is what a human reads in the dashboard), and these
-- rows now say `source = 'home_consultation'`; the /coming-soon waitlist keeps
-- 'website_waitlist'.
--
-- RUN ORDER DOES NOT MATTER. Until this has run, PostgREST rejects a write that
-- names these columns with PGRST204, and the app retries once without them —
-- the same answers are already in `notes`, so no lead is lost to deploy order.
--
-- Measured on kvwsugncsvwvdukdmjij, 2026-09-27: 81 rows, all
-- 'website_waitlist', none carrying a "Destination:" line — nothing to backfill.
-- None of the three names is a Postgres keyword (pg_get_keywords()).
--
-- Additive and idempotent: nullable columns, IF NOT EXISTS. Safe to re-run.
-- (If a column's TYPE ever needs to change, do not edit this file — see
-- docs/known-issues.md §0.)
-- ─────────────────────────────────────────────────────────────────────────────

alter table public.waitlist_signups
  add column if not exists destination text,
  add column if not exists budget      text,
  add column if not exists package     text;

comment on column public.waitlist_signups.destination is
  'Home consultation form: where the student wants to study (free text).';
comment on column public.waitlist_signups.budget is
  'Home consultation form: budget band id (under-300m | 300-500m | 500-800m | over-800m), null if not given.';
comment on column public.waitlist_signups.package is
  'Home consultation form: package of interest (starter | yearly | premium), null if not chosen. Interest only — nothing is charged.';

-- Let PostgREST see the new columns immediately rather than on its next
-- schema-cache refresh.
notify pgrst, 'reload schema';
